### ISSUE TITLE
aws runner how to configure disk size?

### ISSUE THREAD

**Issue by perfgao** [AktechLabs/github-actions-on-windows-azure-example#1]
aws runner how to configure disk size? 

I see that Azure is configured like this:

```
    extra_config:
      storageProfile:
        osDisk:
          diskSizeGB: 512
```

**Comment by aktech** [comment]
Here it is:

```yaml
runners:
  - name: ...
    ...
    extra_config:
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          VolumeSize: 75
          VolumeType: gp2
```
